### ISSUE TITLE
Missing support for req.user

### ISSUE THREAD

**Issue by cjbarth** [types/npm-express#12]
req.user is failing with the error: error TS2339: Property 'user' does not exist on type 'Request'.

http://expressjs.com/en/api.html#app.param

**Comment by felixfbecker** [comment]
Putting the user requested under `req.user` is only an example of a param handler. express itself will never set `req.user` to anything, and we cannot type all possible properties that could be set on `req`. If you use your own param handler, you should type it like this:

``` ts
interface Authenticated {
  user: User
}

app.param('user', (req: Request & Authenticated, res: Response, next: NextFunction, id: string) => {

  // try to get the user details from the User model and attach it to the request object
  User.find(id, function(err, user) {
    if (err) {
      next(err);
    } else if (user) {
      req.user = user;
      next();
    } else {
      next(new Error('failed to load user'));
    }
  });
});

app.get('/user/:id', function (req: Request & Authenticated, res: Response) {
  console.log(req.user)
});
```
