### ISSUE TITLE
http.createServer complains when using this type

### ISSUE THREAD

**Issue by osukaa** [types/npm-express#18]
Hi,

I'm using this type to start a new project I'm working on, but typescript is complaining that the `express.Application` is not compatible with what `http.createServer` is expecting

`Error:(4, 34) TS2345:Argument of type 'Application' is not assignable to parameter of type '(request: IncomingMessage, response: ServerResponse) => void'.`

It seems that the definitely typed repo already fixed this -> https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10676 and here https://github.com/DefinitelyTyped/DefinitelyTyped/issues/10507

Is there a way for that change to be merged here?

**Comment by felixfbecker** [comment]
Please show the code that causes this error.

**Comment by osukaa** [comment]
I have an app.ts file

```
import * as express from 'express';

const app = express();

export default app;

```

and a server.ts file

```
import app from './app';
import http = require('http');

const server = http.createServer(app);

server.listen(3999);
```

my typings.json

```
{
  "name": "node-typescript-example",
  "dependencies": {
    "express": "registry:npm/express#4.14.0+20160925001530"
  },
  "globalDependencies": {
    "jest": "registry:dt/jest#16.0.0+20161025131017",
    "node": "registry:dt/node#6.0.0+20161121110008"
  }
}

```

my tsconfig.json

```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "alwaysStrict": true,
    "noImplicitAny": true,
    "sourceMap": false,
    "typeRoots" : [
      "./typings"
    ]
  }
}
```

**Comment by blakeembrey** [comment]
Just run into this myself - mind if I patch @felixfbecker?

**Comment by blakeembrey** [comment]
Actually, the definition in DefinitelyTyped is terribly incorrect and the "patch" they applied made the definition even more incorrect. I'm going to fix this myself. Basically, Express exports an interface compatible with raw `http` like `(req: IncomingMessage, res: ServerResponse, next?: () => void): void` where `finalhandler` is automatically used when no handler is specified.
