### ISSUE TITLE
Cannot find module 'path-to-regexp'.

### ISSUE THREAD

**Issue by Strate** [types/npm-express#8]
There is an error, I've got using this types

```
typings/modules/express/index.d.ts(1219,30): error TS2307: Cannot find module 'path-to-regexp'.
```

/cc @felixfbecker

**Comment by felixfbecker** [comment]
path-to-regexp is a dependency of express and includes type definitions. I was under the impression that it would pick up the typing a from node_modules. I will look into it. You don't have to cc me btw :D

**Comment by Strate** [comment]
I just cc you because you break it :)
If path-to-regex is express dependency, it could be located at `node_modules/express/node_modules/path-to-regexp`

**Comment by felixfbecker** [comment]
Is that the case in your app? Are you using NPM 2?

**Comment by Strate** [comment]
No just a point :)
In my case I have `path-to-regexp` in my `node_modules`, but I don't have typings for `path-to-regexp`

**Comment by felixfbecker** [comment]
I found the issue. The latest version of express depends on an older version of `path-to-regexp` that does not include the typings yet.

**Comment by felixfbecker** [comment]
@blakeembrey is it possible to add typings from an NPM package as a dependency? Will add it from GitHub as a workaround

**Comment by felixfbecker** [comment]
48ccd5cae75385b37d6b0c03f0e957112f108b04

**Comment by itbrandonsilva** [comment]
Shit, you guys work fast. Ran into this problem before I went to grab some food, and now I'm back and there are no problems. Appreciate the efforts!

**Comment by blakeembrey** [comment]
@felixfbecker Yeah, I think that's the suggested fix also. It's not a great situation, haven't solved it properly unless Typings is refactored to actually use the NPM registry instead of `node_modules/`. In any case, the situation for `@types` works around this.
